language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hello-aws *
  - mkdir -p deploy
  - mv hello-aws.zip deploy/hello-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SCRET_KEY # TRAVIS REPO SETTINGS에 설정된 값
    bucket: hello-aws-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: hello-aws-build # S3 버킷
    key: hello-aws.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: hello-aws # 웹콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: hello-aws-group # 웹콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행완료 시 메일로 알림
notifications:
  email:
    recipients:
      - kmwhng623@naver.com